requires 'EV';
requires 'Promises';
requires 'AnyEvent';
requires 'AnyEvent::Impl::EV';
requires 'DBIx::Class';
requires 'DBD::Pg';
requires 'DBD::mysql';
requires 'strictures';
requires 'Try::Tiny';
